name: Nick D'Amico
email: your.email@example.com
description: >
  Ph.D. Candidate in Political Science studying public opinion and queer politics.

url: "http://localhost:4000" # For local testing, update this when live

baseurl: ""  # if your site is hosted at root

permalink: /:title/

theme: minima  # or minimal-mistakes-jekyll if you install it

plugins:
  - jekyll-feed
  - jekyll-seo-tag
